export const exampleTexts = [
  "He mo‘olelo kēia e hō‘ike ana i ke kumu i mālama loa ‘ia ai ka ipu ‘awa‘awa e kekahi po‘e o Ka‘ū, Hawai‘i. Ua ‘ōlelo ‘ia, he ali‘i wahine ko Ka‘ū i aloha nui ‘ia e kona po‘e kānaka. I ka hāpai ‘ana o ua ali‘i nei, ua hiki mai ka ma‘i ma luna ona, a i ke kokoke ‘ana aku i ka wā e hānau ai, ua make ihola ke ali‘i wahine. Ua lawe ‘ia kona kino i loko o ke ana. Ua ‘oloka‘a ‘ia ka pōhaku nui a pa‘a ka waha o ka lua.",
  "I ka hiki ‘ana mai o ka lā e hānau ai ‘o ke keiki, ua ‘ō‘ili mai ka mu‘o mai ka piko mai o ke ali‘i make, a ulu a puka ma kekahi hakahaka ‘u‘uku ma ka ‘ao‘ao o ka pani o ka lua, a kolo aku nei no kahi mamao loa aku. I kekahi kakahiaka ua ‘ike akula ke ali‘i o ka hiku o nā ahupua‘a i kolo ‘ia e ka ipu ‘awa‘awa i ka ulu maika‘i mai ma hope aku o kona hale.",
  "Ua mālama ‘ia e ia a hiki i ka pua ‘ana a hua. I ke o‘o ‘ana iho, ua hele mau ‘o ia i nā lā a pau e kīkēkē, e ‘iniki, e nānā ai inā i o‘o maika‘i e kahakaha ‘ia ai. ‘A‘ole i ‘ike kēia ali‘i he ipu ‘awa‘awa kanaka kēia.",
  "Ua ho‘i ka ‘uhane o kēia ipu ‘awa‘awa i luna o kekahi haka a hō‘ike aku nei i kona ‘iniki ‘ia, a ua nui ka ‘eha. Ki‘i ‘ia ke kahuna o kēlā wahi a ua hō‘ike ‘ia iā ia e ka ipu ‘awa‘awa nā mea i hāhā ‘ia ma luna o kona kino, me ke kauoha pū aku iā ia e ‘imi a loa‘a ‘o ia a ho‘iho‘i mai. Ua iho ke kahuna a ka lua pao, a ma laila ‘o “ia i ho‘okolo ai ma ke kā o ka ipu ‘awa‘awa, a hiki i ka hiku o nā ahupua‘a.",
  "I ka ‘ike ‘ana o ke ali‘i iā ia ma kahi o ka ipu ‘awa‘awa, nīnau maila ‘o ia no ke aha ‘o ia nei i hiki aku ai. Hō‘ike aku nei ua kahuna nei i ka hō‘ike a kona haku iā ia. Ua piha ke ali‘i i ka minamina i kona nānā ‘ana iho i ka maika‘i o ka ipu ‘awa‘awa, a hō‘ole aku nei i ka mana‘o o ke kahuna.",
  "Ua lilo ihola kēia i kumu no lāua e ho‘opa‘apa‘a ai a hiki i ka ‘ōlelo ‘ana aku o ke kahuna e hele lāua a ‘ike pono ‘o wai ka i kuleana ‘i‘o i ua ipu ‘awa‘awa lā; ‘o ke kumu mai, no ka hilina‘i ‘ole o ke ali‘i he kanaka nō kēia ipu ‘awa‘awa. I ka ‘ae ‘ana o ke ali‘i, ua hele lāua e ‘ike i kahi i kupu a‘e ai ‘o ua ipu ‘awa‘awa lā. Ua hele lāua ma ka ‘ao‘ao o ke kā a hiki i ka lua pao, a komo aku nei i loko. Ua ‘ike like aku nei nō lāua i kahi i ulu mai ai ‘o ka ipu ‘awa‘awa, mai ka ‘ōpū mai o ke ali‘i make.",
  "Ua ho‘iho‘i ‘ia mai ka ipu ‘awa‘awa e ke kahuna a mālama ‘ia me ka punahele loa a hiki i ka make ‘ana o ua kahuna nei. Ma hope mai o ia manawa, ‘a‘ole i maopopo he aha lā ka mea i hana ‘ia no kēlā ipu ‘awa‘awa.",
  "No ka ‘ohana o kēlā wahine ali‘i i make, ua lilo loa ka ipu ‘awa‘awa i mea nui iā lākou. Ke nahā kā lākou ipu ‘awa‘awa, ua kanu ‘ia me ka maika‘i, a i ‘ole, ua puhi ‘ia i ke ahi i ‘ole e kāpulu ‘ia. Ke nīnau ‘ia aku ke kumu o lākou i kiloi wale ‘ole ai i nā ‘āpa‘apana o kā lākou ipu ‘awa‘awa, ho‘okahi nō pane e loa‘a mai, “No ka hiku o nā ahupua‘a.”",
];


export function getRandomExample() {
  return exampleTexts[Math.floor(Math.random() * exampleTexts.length)];
}